name: keep_it_clean
description: Keep it clean. Trova il cestino per la raccolta differenziata più vicino a te.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.1+11

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl:
  cupertino_icons: ^0.1.2
  google_maps_flutter:
  permission_handler: 5.0.1
  shared_preferences: ">=0.5.0+1 <2.0.0"
  simple_animations:
  firebase_core: ^0.4.3+1
  cloud_firestore: ^0.13.7
  firebase_storage: ^3.1.0
  firebase_auth: ^0.16.1
  google_sign_in:
  flutter_facebook_login: ^3.0.0
  location: ^2.3.5
  url_launcher: ^5.4.1
  flutter_swiper:
  path_provider:
  http:
  image_picker:
  auto_size_text: ^2.1.0
  path:
  flutter_launcher_icons:
  smooth_page_indicator: ^0.1.3
  flutter_device_type: ^0.2.0

  ### REFACTORING ###
  stacked:
  auto_route: 0.5.0
  stacked_services:
  get_it:
  injectable:
  geoflutterfire: ^2.1.0
  flutter_hooks:
  stacked_hooks:
  observable_ish:
  easy_localization: ^2.3.2
  tutorial_coach_mark: ^0.3.0
  apple_sign_in: ^0.1.0
  device_info: ^0.4.1+4


flutter_icons:
  android: true
  ios: true
  image_path: "assets/keep_it_clean_logo.png"
  image_path_ios: "assets/keep_it_clean_logo_ios.png"
#  adaptive_icon_background: "#FF5B9C64"
  adaptive_icon_background: "#FF449E64"
  adaptive_icon_foreground: "assets/keep_it_clean_logo_adaptive.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  mockito:
  auto_route_generator: 0.5.0
  injectable_generator:

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/illustrations/
    - assets/icons/
    - assets/maps_markers/
    - assets/translations/
    - assets/default-bin-photo.png
    - assets/loading.gif
    - assets/badge.png
    - assets/keep_it_clean_logo.png
    - assets/keep_it_clean_logo_ios.png
    - assets/keep_it_clean_logo_adaptive.png
    - assets/keep_it_clean_only_logo.png
    - assets/no-avatar.jpg

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true





  fonts:
    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcons.ttf


    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
        - asset: fonts/Montserrat-Medium.ttf
        - asset: fonts/Montserrat-SemiBold.ttf

